version: '3.8'

services:
  Shopping_Cart:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: Shopping_Cart
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development